# Generated by Django 5.2 on 2025-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics_sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesnetwork",
            name="debt",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=15, verbose_name="Задолженность перед поставщиком"
            ),
        ),
    ]
